[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "b5c94438cbe90f256f82c5eb04f5be5928683beb"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "fb8d7051f976c9834bbaa552164ca68f997ca83eb206babd8b74502de0a11d04"
    url = "https://github.com/maleadt/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.4.0+0/oneAPI_Support.v0.4.0.x86_64-linux-gnu.tar.gz"
