[[oneAPI_Support]]
arch = "x86_64"
git-tree-sha1 = "c834e5913bd3a3923a5029184fba0ad0af2d08e6"
libc = "glibc"
os = "linux"

    [[oneAPI_Support.download]]
    sha256 = "4405f4568f83fae5e31a1039be4d9dcbcd9315379402ed3764771abac9f87be8"
    url = "https://github.com/maleadt/oneAPI_Support_jll.jl/releases/download/oneAPI_Support-v0.4.0+0/oneAPI_Support.v0.4.0.x86_64-linux-gnu.tar.gz"
